#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.jsx" "*.ts" "*.tsx" "*.json" "*.css" "*.scss" "*.md" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --single-quote --trailing-comma all --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
